version: '3'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    container_name: server

  client:
    build: ./client
    depends_on:
      - server
    container_name: client
